# Configuration for development (dev server and hot reloading)
version: "3.7"

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=${DATABASE_NAME-postgres}
      - POSTGRES_USER=${DATABASE_USER-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD-postgres}
    container_name: db

  web:
    build:
      context: .
      args:
        - LIBMARK_VERSION=e3cc4bbe82a44d94edac2d9eba7455c2d12cfe01
    environment:
      - DATABASE_NAME=quantumdb
      - DATABASE_USER=quantumuser1
      - DATABASE_PASSWORD=hauki
      - DATABASE_HOST=192.168.1.248
      - DATABASE_PORT=5432
      - BROKER_URL=pyamqp://guest@rabbitmq//
      - SECRET_KEY=${SECRET_KEY-secret}
      - API_KEY=${API_KEY-secret}
      - DEBUG=True
    command: sh -c "
      python manage.py makemigrations WebCLI &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    container_name: web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

