version: "3.8"

services:
  quantmark2-web:
    build:
      context: .
    environment:
      - DEBUG=True
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
