version: "3.9"

services:
  web:
    build:
    environment:
      - DEBUG=True
    command: sh -c "
      python manage.py makemigrations WebCLI &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    container_name: web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
