version: "3.8"

services:
  qleader-db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=quantdb
      - POSTGRES_USER=quantuser
      - POSTGRES_PASSWORD=greatsecret # Must be properly defined in the production!
    container_name: qleader-db
    
  qleader-web:
    build:
      context: .
    environment:
      - SECRET_KEY=secret # Must be properly defined in the production!
      - DEBUG=True
      - DATABASE_NAME=quantdb
      - DATABASE_USER=quantuser
      - DATABASE_PASSWORD=greatsecret
      - DATABASE_HOST=qleader-db
      - DATABASE_PORT=5432
    command: sh -c "
      python manage.py makemigrations qleader --noinput &&
      python manage.py migrate --noinput &&
      gunicorn -b 0.0.0.0:8000 webmark2.wsgi"
      # python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - qleader-db
