version: "3.8"

services:
  quantmark2-web:
    build:
      context: .
    environment:
      - SECRET_KEY="secret" # Should be specified correctly when used in production.
      - DEBUG=True
    command: sh -c "
      python manage.py makemigrations qleader &&
      python manage.py migrate --noinput &&
      gunicorn -b 0.0.0.0:8000 webmark2.wsgi"
#      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
