name: Docker publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, review_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run migrations
      run: |
        touch .env
        echo SECRET_KEY=secret >> .env
        python manage.py makemigrations qleader
        python manage.py migrate
    - name: Lint with flake8
      run: flake8 . --show-source --statistics
    - name: Lint with curlylint
      run: curlylint templates/
    - name: Test with Django
      run: |
        coverage erase
        coverage run manage.py test
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - name: Set up QEMU
      if: ${{ github.event_name == 'push'}}
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      if: ${{ github.event_name == 'push'}}
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: ${{ github.event_name == 'push'}}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build WebMark and push
      if: ${{ github.event_name == 'push'}}
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: blakaut/qleader:latest
